name: portainer_license
version: 0.1.0
title: Portainer License Monitoring
author: Manuel "Overlord" Michalski
description: Checkmk special agent for monitoring Portainer license expiry and node usage via API.
license: Apache-2.0
min_version: 2.4.0
edition: cre,cee
